### DISCUSSION TITLE
Which sensors represent Grid consumption and Solar production?

### DISCUSSION THREAD

**Discussion by cayossarian** [SpanPanel/span#65] [Q&A]
Understanding SPAN Panel Integration in Home Assistant: Grid and Solar Production

These two aspects—grid power and solar production—are interrelated because solar generation offsets grid consumption, and in some cases, excess power is stored in batteries or exported back to the grid.

What your energy dashboard needs in order to provide reporting is:

1.  How much solar you are generating, which for you depends on where your system is reporting this figure. If you don't see solar in your app you might be able to use data from the solar inverter (if it has a Home Assistant integration) or look how they wired the solar into your panel.  You are looking for energy figures which are either kWh or Wh for the dashboard.  If the installer wired the solar into circuits, like 30/32, you can set up the options in the HACs integration to track those values via generated sensors. If the solar is not wired into circuits then you'll need to get the energy values from the inverter.
2.  How much power you are using from the grid factoring in solar production (from when the current_power is positive)
3.  How much power you send back to the grid (when the current_power is negative)

### Solar Energy

For item 1 you'll need a way to get solar energy.  At the time of this writing, the SPAN API does not directly expose solar production data. However, solar inverters may still feed power into the SPAN panel through dedicated circuits, which can be identified in the SPAN app.
	•	If your solar system is connected to individual circuits (lugs) in the panel, this SPAN panel integration allows you to designate these as solar circuits in its Home Assistant integration. This enables the creation of sensors for tracking solar production.
	•	If your solar system is not wired directly to SPAN-monitored circuits (e.g., connected via a sub-panel), you will need to use a separate integration for your inverter in Home Assistant. In this case, solar production data must be merged manually with SPAN’s grid consumption data to get a full picture.

A complete understanding of your system’s configuration—where energy is generated and how it reaches your SPAN panel—is necessary for accurate tracking. The key data points available from the SPAN integration include:
	•	Current Power (sensor.span_panel_current_power) – Net power consumption (positive) or export (negative).
	•	Battery sensors (sensors optionally enabled) – If batteries are in use, they may alter grid consumption calculations.
	•	Solar production sensors (if configured) – Monitors solar circuits if directly wired to SPAN.d

### Grid Energy

For items 2 and 3, you can easily use the main meter Energy values directly to get energy going in and out of your house and if your inverter is producing Energy (Wh or kWh) figures use those in the energy dashboard.  These sensors are:
```
    sensor.span_panel_main_meter_produced_energy (Energy exported to the grid)
    sensor.span_panel_main_meter_consumed_energy (Energy imported form the grid)
```

### Calculating Grid Usage and Solar Export that matches what your utility reports

The utility company uses data warehousing to calculate costs while the SPAN panel is producing numbers that are more accurate but don't necessarily match the utility reporting.  If you're looking to double check or verify SPAN reporting against the utility metrics you will need to use an approach similar to that of the utility company.  In order to calculate these numbers with the same statistical methods the utility uses you can start with the sensor for current_power and convert it to energy (import being positive and negative being export to the grid).

The following Home Assistant templates provide a starting point for tracking grid power consumption and solar export and reporting those the way the utility company does.  This approach is not necessary to track energy usage in general and is really only provided for comparing figures with that the utility might provide in its billing.   These calculations use what is most typical energy company’s billing methods, using Left-Riemann sum approximations.

```yaml
- sensor:
    # From template.yaml
    # When the current_power is positive it means the house is importing power from the grid
    # Used to compute "Energy Spent kWh" in sensors.yaml
    - name: Grid To House Watts
      unique_id: sensor.grid_to_house_watts
      device_class: power
      state_class: measurement
      unit_of_measurement: W
      state: >
        {% set state_val = states('sensor.span_panel_current_power') %}
        {% if state_val is match("^-?\\d+(\\.\\d+)?$") %}
          {% set float_val = state_val | float %}
          {{ [0, float_val] | max }}
        {% else %}
          0
        {% endif %}

      # From template.yaml
      # When the current_power is negative it means the house is exporting power to the grid
      # solar sold represented as an absolute value
    - name: Solar Sold Watts
      unique_id: sensor.solar_sold_watts
      device_class: power
      unit_of_measurement: W
      state: >
        {% set state_val = states('sensor.span_panel_current_power') %}
        {% if state_val is match("^-?\\d+(\\.\\d+)?$") %}
          {% set float_val = state_val | float %}
          {% if float_val < 0 %}
            {{ float_val | abs }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}


# From sensors.yaml, used to match the Left-Riemann Sum that the energy company utilizes in their data warehouse
- platform: integration
  source: sensor.grid_to_house_watts
  name: Energy Spent kWh
  unique_id: sensor.energy_spent_kwh
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.span_panel_solar_inverter_instant_power
  name: Solar Inverter Produced kWh
  unique_id: sensor.solar_inverter_produced_kwh
  unit_prefix: k
  round: 2
  
- platform: integration
  source: sensor.solar_sold_watts
  name: Solar Sold kWh
  unique_id: sensor.solar_sold_kwh
  unit_prefix: k
  round: 2
```

These sensors can be used directly in Home Assistant’s Energy Dashboard to compare your energy usage against your utility provider’s data.

In summary, correctly interpreting grid power consumption and solar production within Home Assistant’s SPAN integration depends on how your system is wired. If solar circuits are directly wired into lugs this, SPAN integration can track production; otherwise, an external inverter integration is needed. Understanding how power flows through your panel will allow for accurate monitoring and energy management.
